name: destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
#    if: false
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: 1.3.0
#          cli_config_credentials_token: 
      - name: GET Root_DB
        run: |
          MASTER=`curl  --header "X-Vault-Token: ${{ secrets.VAULT_TOKEN }}"  https://vault.apr.vee.codes/v1/root_db/data/secret?version=1 |jq -r .data.data.master` 
          echo $MASTER
          echo "master=$MASTER" >> $GITHUB_ENV
      - name: Write default file
        run: | 
          yq e '.vault_token = "${{ secrets.VAULT_TOKEN }}" ' -i config/defaults.yml
          yq e '.password = "${{  env.master }}" ' -i config/defaults.yml
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
            plan.cache
          key: terraform-lock-${{ github.event.workflow_run.head_branch }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform destroy
        run: |
          terraform init
          terraform destroy -auto-approve
